cc_test(
    name = "sample-test",
    srcs = ["sample_test.cc"],
    deps = [
        "@gtest//:gtest",
    ],
)

cc_test(
    name = "BinaryBlobTest",
    srcs = ["BinaryBlobTest.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//src:BinaryBlob",
    ],
)

cc_test(
    name = "UtilsTest",
    srcs = ["UtilsTest.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//src:utils",
    ],
)