cc_test(
    name = "BinaryBlobTest",
    srcs = ["BinaryBlobTest.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//src:BinaryBlob",
    ],
)

cc_test(
    name = "BlockTest",
    srcs = ["BlockTest.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//src:BinaryBlob",
        "//src:Block",
    ],
)

cc_test(
    name = "UtilsTest",
    srcs = ["UtilsTest.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//src:utils",
    ],
)